### ISSUE TITLE
Running it on android

### ISSUE THREAD

**Issue by Weepiez** [TeamFightTacticsBots/Alune#12]
How can I run it directly on my phone?

**Comment by akshualy** [comment]
At the moment there is no support for ADB over USB, so you'd have to be in the same network as your PC and find out what your IP address is (for example, by logging in to your router and checking the connected devices). If your device is connected via USB, you can also find out the IP by using ADB shell:
```
adb shell ip route | awk '{print $9}'
```
Then enable ADB on port 5555:
```
adb tcpip 5555
```

Long term I'd like to enable support for USB, but it's not a priority for me right now.

**Comment by RomeoAlphaEkko** [comment]
So one could use an old phone place it at home in the same wlan and skip the emulator?

**Comment by akshualy** [comment]
Yes, that's the beauty about ADB.
One small caveat I failed to mention in my initial reply is that we do change the resolution. You will have to manually reset this at the moment if you care about using the phone afterward.
In an adb shell connection to your phone, you may use:
```
adb shell wm size reset
adb shell wm density reset
```
