### ISSUE TITLE
Info - Event Mode not normal

### ISSUE THREAD

**Issue by RomeoAlphaEkko** [TeamFightTacticsBots/Alune#15]
while i do not see it as a problem, just that it is noted the event mode is played not the normal game mode (most left mode to choosable)

**Comment by akshualy** [comment]
I don't have the time to check it out at the moment, does it break or do anything out of the ordinary in the event mode? I can add a fix for it at some point, but if it's not breaking I don't see any urgency.

**Comment by RomeoAlphaEkko** [comment]
I had it only running for a game or two didn't look like breaking anything just wanted to mention it,

And with the birthday celebrations there will be another mode in June, have not seen it yet

Will test it with the pass release this evening and if something is broken come back
