### ISSUE TITLE
ValueError when parsing installed TFT app version

### ISSUE THREAD

**Issue by novak24611** [TeamFightTacticsBots/Alune#17]
I followed the steps but it still doesn't work. Can you help me please
![123](https://github.com/TeamFightTacticsBots/Alune/assets/64787005/c1b3beb4-9bce-4179-a276-fad44fde698c)

**Comment by akshualy** [comment]
I tried with the most recent version and it seems to work.
So something is wrong with your installed TFT app version (or what ADB is reporting it to be), if you installed via Google Play try from APKMirror or vise versa. If the problem persists, you could add a debug statement to print version_two_parts: `logger.info(version_two)` in `is_version_string_newer` and debug from there.

**Comment by novak24611** [comment]
I also downloaded it from google play but it still doesn't work and adb doesn't work. I don't know if something is missing or not. I just followed the steps you gave.

**Comment by akshualy** [comment]
Which Emulator are you using? As I said, it's doing something weird in reporting your TFT app version. I've tried on BlueStacks and LDPLayer9 and both work fine as of right now.

If you don't want a proper fix or don't want to bother debugging, you can temporarily add a `#` in front of the lines 360 and 361 in `main.py`. That'll disable the TFT app version check.

**Comment by novak24611** [comment]
Can you be specific? Because I'm very bad at English. I tried LD Player and it still works, even bluestack does.

**Comment by akshualy** [comment]
I'm not sure I can be more specific than I was in that above sentence, use DeepL to translate it into your language.

**Comment by JokoKenguru** [comment]
Has the project gone into hibernation?)

**Comment by akshualy** [comment]
> Has the project gone into hibernation?)

Not really, I just did not work on it since no urgent update was needed.
