### ISSUE TITLE
Adding second trait

### ISSUE THREAD

**Issue by thanhdtr** [TeamFightTacticsBots/Alune#23]
Is there any way I can add the 2nd trait for bot to pick ? I tried to modify the config.yaml
traits:
  - heavenly
  - ghostly
 
 and the images.py 
def get_default_traits(cls):
      
        return [cls.HEAVENLY,
                cls.GHOSTLY,]
    HEAVENLY = auto()
    GHOSTLY = auto()
and adding the trait image but nothing works.

**Comment by akshualy** [comment]
What you did sounds about right, but if you want to make sure open a pull request or link to a commit in a fork of yours so I can take a second look.

**Comment by akshualy** [comment]
Hi, closing this. You can refer to #28 to see how to add new traits.
