### ISSUE TITLE
Check Queue Time

### ISSUE THREAD

**Issue by Zhanyee** [TeamFightTacticsBots/Alune#24]
Sometimes TFT puts us in a queue that we never find, possibly an anti-bot measure, this evening it happened twice that I opened TFT and was in queue for more than 160 minutes.

It would be good for Alune to check if the queue exceeds 5 minutes, the bot cancels the queue and puts it in the queue again, so that TFT thinks that there really is a person playing and the bot doesn't stop.

**Comment by akshualy** [comment]
Yup, good idea! Will look into it soon :)

**Comment by StanleyAlbayeros** [comment]
heyo @akshualy  i [opened a PR](https://github.com/TeamFightTacticsBots/Alune/pull/90https://github.com/TeamFightTacticsBots/Alune/pull/90) for this :)

**Comment by akshualy** [comment]
Implemented in #90 , available from source, available from exe within the next few days.
