### ISSUE TITLE
Are you thinking of developing a TFT bot for 12 seasons as well?

### ISSUE THREAD

**Issue by rayhahn** [TeamFightTacticsBots/Alune#25]
I think tft ocr has stopped developing, so I need a bot for the new TFT season. Are you thinking of developing it?

**Comment by RomeoAlphaEkko** [comment]
It will probably only need a new working trait

Or the swap/upgrade to the Teamplaner to work

**Comment by Kyrluckechuck** [comment]
What @RomeoAlphaEkko mentioned is correct -- each season there are only a small handful of changes that are typically required, and mid-set updates typically only require a new trait that has a "high-ish" win rate updated
