### ISSUE TITLE
S12 is here - test run

### ISSUE THREAD

**Issue by RomeoAlphaEkko** [TeamFightTacticsBots/Alune#27]
- chooses game mode ✔
- starts game ✔
- accepts game invite ✔
- rerolling augments ✔
- buying xp ✔
- leaving game and requeing ✔

- not working buying aka new traits -> needs either teamplanner (would need teamplaner icon, 2-star (levelup) and maybe even 3-star level up || or new trait screenshotted (i already failed trying to take them before T_T ) ❌
- - if staying with traits hthere are multible with 2 grey and green (1 and 2 cost) ( https://tactics.tools/info/traits ) (screenshots with examples below)

- running in the caroussel -> it ran outside the circle past the  circle with the champions ❌ (2nd caroussel it ran earlier, missed on the first run to the top left, hit the circle on the way back to bottom right) 

- boni option: buying charms (s12 specific)

Trait Examples:
![Screenshot_2024 07 31_15 15 10 300](https://github.com/user-attachments/assets/6fd43efa-6c8d-4a49-b4b9-4d3aa805477a)
![Screenshot_2024 07 31_15 24 01 250](https://github.com/user-attachments/assets/2b6bddf8-3484-4bb7-8788-417bfe629f16)

Teamplanner:
![Screenshot_2024 07 31_15 27 04 284](https://github.com/user-attachments/assets/6e1b0e35-c136-4861-9b02-5f7e81f06dcf)

2-Star:
![Screenshot_2024 07 31_15 26 12 333](https://github.com/user-attachments/assets/86f591e9-4f54-4505-a9ca-5a82a97dd58d)

3-star:
![Screenshot_2024 07 31_15 38 57 883](https://github.com/user-attachments/assets/9e99eed5-7444-4dd9-a118-eb5c69f4f978)

hope this at least helps a bit...

**Comment by akshualy** [comment]
Thanks for the extensive overview! I'll need to play a few rounds to decide on a decent trait, I'll close this in favor of #26 since it's the same topic, but this is very much appreciated!
