### ISSUE TITLE
S12 update - faerie not working

### ISSUE THREAD

**Issue by RomeoAlphaEkko** [TeamFightTacticsBots/Alune#29]
hi,

first thank you for the update

have run a few "test games"

- faerie seems not to be bought, had seraphines and kalistas which saw, not being bought

- incarnator and witchcraft were being bought

 the bench was 30-50% filled when i died

**Comment by akshualy** [comment]
> faerie seems not to be bought, had seraphines and kalistas which saw, not being bought
Yes, it's not part of the default traits. Did you change the config for it to buy Faerie?

**Comment by RomeoAlphaEkko** [comment]
ah that explains it, just checked which of the trait icons got bought :D
