### ISSUE TITLE
Do not exit the bot on minor app version mismatch

### ISSUE THREAD

**Issue by MisterRath** [TeamFightTacticsBots/Alune#30]
Hi there is a new patch that went live, leading the bot to be outdated. Is it posible to patch the bot ?

**Comment by MisterRath** [comment]
Hi again, I've read the code to understand what was the problem and found out that even tho we have the latest patch of tft it blocked and returned error "new version stuck in queue blabla". So to bypass this problem I have just change the raise_and_exit into a logger.info in main.py in order to let the programm run.
But the problem of version checker is still here.

**Comment by akshualy** [comment]
Hey, that error only happens when your TFT app package version is smaller than the one listed in the global Google Play store. If you installed through Google Play, try restarting the Google Play app to check for the update. The UI is a bit weird sometimes.
