### ISSUE TITLE
I got this when i run Alune.exe (WARNING  - Failed to connect to ADB session with device localhost:5555), what i should do

### ISSUE THREAD

**Issue by Taitran-CTRL** [TeamFightTacticsBots/Alune#31]

**Comment by ducanlove** [comment]
you need install Bluestacks and turn on ADB.

**Comment by akshualy** [comment]
Which emulator are you using?

**Comment by Taitran-CTRL** [comment]
> Which emulator are you using?

Im using ldplayer 9, does it work?

**Comment by akshualy** [comment]
That one should work, can you follow the wiki for these steps and check if it still does not work?
https://github.com/TeamFightTacticsBots/Alune/wiki/ADB-Port#platform-tools

**Comment by akshualy** [comment]
Please reopen if enabling ADB and or following the above steps did not work.
