### ISSUE TITLE
How to change traits config

### ISSUE THREAD

**Issue by ducanlove** [TeamFightTacticsBots/Alune#34]
Hi,
by default in the config file i see it is 'witchcraft' and 'incantor'.
i want to change this value to 'portal' and 'scholar' but it doesn't work.
i added images for these 2 traits but the bot doesn't work.
why?

![portal](https://github.com/user-attachments/assets/f2719d1b-9b7b-4314-9559-9f6029090473)
![scholar](https://github.com/user-attachments/assets/b59f5ef4-d87c-4a4c-936c-965d557352a5)

![image](https://github.com/user-attachments/assets/ba4e2172-7241-4592-bcbb-b7c15f64d7fd)

**Comment by akshualy** [comment]
You can refer to #28 to see the places where images are in the code. If you want to know why yours doesn't work, I need to see your code. Feel free to create a fork and commit your changes there.
