### ISSUE TITLE
Surrender as soon as possible

### ISSUE THREAD

**Issue by akshualy** [TeamFightTacticsBots/Alune#4]
I want the bot to be able to surrender as soon as possible (the round after krugs), so that I can farm TFT pass experience more efficiently.

Estimate of what's needed:
- Recognition of when we are in a round that we can surrender in - Checking the settings menu for the colored surrender button may be enough.
- Clicking the settings button
- Clicking the surrender button
- Clicking the confirm surrender button

After that, the existing logic should catch the post game state.

**Comment by RomeoAlphaEkko** [comment]
just the reminder one needs both options, full game for league pass, short games for tft pass

**Comment by ducanlove** [comment]
How to set bot to surrender as soon as possible for tft pass.?

**Comment by akshualy** [comment]
Right now it's not implemented yet.

**Comment by akshualy** [comment]
Implemented in #36
