### ISSUE TITLE
Improve ease of switching between playing out games and surrendering

### ISSUE THREAD

**Issue by RomeoAlphaEkko** [TeamFightTacticsBots/Alune#41]
as in the last update the ff function was added for manual usage

with the new battlepass being dropped in 7 days

as an idea: create two .exe one for 10 min games and fast pass xp gain and the other one for the event passes like the upcoming worlds pass

or one can use them in combination for better event token gain (manually)

**Comment by Kyrluckechuck** [comment]
Eh, at most I'd recommend this be added as a flag provided to the executable

**Comment by RomeoAlphaEkko** [comment]
well launching the executable and getting asked would be perfect

```
press: 
[0] for Never Surrender, die in glory 
[1] as fast out of here as possible
_
```

**Comment by akshualy** [comment]
I think for the state the bot is at, the config is enough.
The only improvement I see reasonable here is to print out the chosen surrender type (like in the previous bot) and clarify which pass type the current forfeit option is recommended for. i.E. "The bot will surrender as soon as possible, which is recommended for farming TFT passes." vs. "The bot will play out games, which is recommended for farming event passes." or something along those lines.

However, I am more than happy to support a UI in which the forfeit option is a checkbox in the future.

**Comment by akshualy** [comment]
The bot now logs which surrender mode is for recommended for what, anything else will have to wait for a UI implementation of the config. Closing it for now.
