### ISSUE TITLE
it didn't work at this part

### ISSUE THREAD

**Issue by koname1231** [TeamFightTacticsBots/Alune#42]
![image](https://github.com/user-attachments/assets/5224c7a2-ad8c-4a77-904b-4a8aa575c1ae)
when game is done it doesn't click one more time button and it can't repeat the program

**Comment by akshualy** [comment]
Please upload the latest debug log file from the logs folder in the alune-output folder.

**Comment by koname1231** [comment]
[2024-09-21_11-03-30_051975.log](https://github.com/user-attachments/files/17082519/2024-09-21_11-03-30_051975.log)

**Comment by akshualy** [comment]
I can't see anything wrong in the logs, are you playing the game in English?

**Comment by koname1231** [comment]
no in korean because i don't know how to change it

**Comment by koname1231** [comment]
is this didn't work at windows 11?

**Comment by akshualy** [comment]
> no in korean because i don't know how to change it

The TFT app language is determined by your phone's language, you can change it under `Settings > System > Language & input > Language`.

> is this didn't work at windows 11?
Which windows version you use does not matter.

**Comment by koname1231** [comment]
so thank you !! it works perfectly . i can use this by pay 5$ per month !!

**Comment by akshualy** [comment]
There's no need to pay ^^ But good to know it works!
