### ISSUE TITLE
Loading screen visual bug?

### ISSUE THREAD

**Issue by blueblueblueblueblu** [TeamFightTacticsBots/Alune#50]
Sorry in advance - this is my first time using Github for anything.

I started using the app three days ago and everything was working fine around then. Starting yesterday, though, every game I "get into" remains in this state. It seems to still be progressing and going through as normal, though; it's just that I can't observe anything. I suppose I should also mention that I'm using the newest version of Bluestacks, and, of course, I've got the most recent version of the .apk and the .exe.

**Comment by blueblueblueblueblu** [comment]
Here's another picture for what it ends up looking like after the game ends: 
![image](https://github.com/user-attachments/assets/92c5a9d9-605c-4f1f-ab2d-0d32c97dcfe4)

after this, I have to press 'Exit Now' manually, at which point the bot resumes like normal... until it gets stuck in the loading screen once again.

**Comment by Mythilily** [comment]
I use a different emulator and have seen this happen every now and then as well. I think it started after the last minor TFT update, but might be wrong about that.

**Comment by akshualy** [comment]
Hi, I removed the images for your own accounts safety. Remember to black out names on screenshots.

In any case, that's an interesting issue that I don't think is with Alune, but I'll have more time to investigate after the weekend. In the meantime, all advice I can offer is to try a different emulator or a different TFT app version, if possible.

**Comment by blueblueblueblueblu** [comment]
Oh, right. Sorry, I'm a little stupid sometimes. Thanks for looking out.

I'll try to revert to before the Oct. 1 micropatch tonight and see if it makes any difference, and if I find any other suitable emulator, I'll try that out, too. I'll try to post the results tomorrow if I notice that fixes the problem.

**Comment by akshualy** [comment]
Can not reproduce with version [14.19.6223713](https://www.apkmirror.com/apk/riot-games-inc/teamfight-tactics-league-of-legends-strategy-game/teamfight-tactics-league-of-legends-strategy-game-14-19-6223713-release/tft-teamfight-tactics-14-19-6223713-android-apk-download/) on LDPlayer; what's your app version and emulator?

**Comment by blueblueblueblueblu** [comment]
Hi. I had been using the latest .apk on the website linked in the setup guide and I was using bluestacks' latest version as the emulator, too. I uninstalled it and tried out LDplayer after you made your post and, after five or six hours of testing, it seems to be working fine. To add some random speculation, I figure it's either an issue with bluestacks specifically or maybe it's just my PC not having good specs - I'm only really working with a 1060 and an i4790, so LDplayer using less resources theoretically is what'd be solving it here. Either way, thank you for the suggestion and fast reply.

**Comment by akshualy** [comment]
Thanks for the update! I'll note down somewhere that PC performance may be an impacting factor on your choice of emulator.
