### ISSUE TITLE
ban rate 

### ISSUE THREAD

**Issue by Jokiblack** [TeamFightTacticsBots/Alune#53]
Hello, I wanted to know if anyone has suffered from any ban, due to the emulator issue and that it is more complex to detect this type of bots on Android, but I wanted to know if anyone has had problems, since I did have problems with the Windows version. And don't you have a discord? for news etc. and questions

**Comment by akshualy** [comment]
No bot has been reported to us yet. I have a personal Discord, but anything relevant will be noted on GitHub.
