### ISSUE TITLE
1.05 dawn of heroes no reqeue 

### ISSUE THREAD

**Issue by RomeoAlphaEkko** [TeamFightTacticsBots/Alune#62]
good morning,

while for normal mode ff + starting a new game works,
once you swap to the new game mode it no longer does
it still surrenders but is stuck in the post game lobby

![image](https://github.com/user-attachments/assets/8d7b1f86-c77c-49e1-8769-1506a82b940c)

once this click is done (manually) it works again

**Comment by akshualy** [comment]
Discovered the issue, it's getting stuck because of the surrender mode. There is no exit now button when surrendering, so the bot is still stuck in the in-game decision loop and doesn't recheck the other app states. I'll resolve this soon.
