### ISSUE TITLE
Manually set local port for ADB connection

### ISSUE THREAD

**Issue by muitenphale** [TeamFightTacticsBots/Alune#66]
Please allow to set local port manually on start up. This will help to run multiple instances of android simulator on a same computer. For now, I still can workaround by running simulator instance with the highest port number first then run Alune to let it scan port then run the other simulator instance then another alune but sometimes it just uses the same port number.

**Comment by akshualy** [comment]
Ah yes, I wanted to do this but forgot to. Sorry for the inconvenience! Will get on it.
