### ISSUE TITLE
ERROR with Accepting queue

### ISSUE THREAD

**Issue by jppuzzle** [TeamFightTacticsBots/Alune#74]
Seems like the bot is not detecting that the play button has been pressed and does not proceed to accept once prompted and loops indefinitely, i have just updated to the latest version so not sure what the issue might be.
.
![123](https://github.com/user-attachments/assets/e2bc6a42-8317-4b65-a62b-abdb96cb181b)

**Comment by akshualy** [comment]
From where are you starting Alune? Is it clicking the Start Queue button itself? As you can see it's recognizing the lobby screen as the main menu screen, so it may be worth to start it from main menu instead.

**Comment by jppuzzle** [comment]
so basically, the bot will get into the normal game lobby fine and will click play, then when the queue pops it never accepts, leading to the queue expiring and back to lobby screen then bot will click play again, then it repeats itself in a loop. Should I start alune from a different page? I usually always load tft first and open alune when TFT is in the home page.

**Comment by jppuzzle** [comment]
actually, thank you for the input, I am unsure what I did before that failed this task, but with your tip it seems to have fixed it, will close the issue now thank you!

**Comment by jppuzzle** [comment]
resolved!
