### ISSUE TITLE
Run Alune while playing League of Legends

### ISSUE THREAD

**Issue by lolol0l** [TeamFightTacticsBots/Alune#79]
Hello, is it okay to run Alune while playing League of Legends?
I know it doesn't affect League at all, but I'm worried that Vanguard might detect it as a cheating program.
Alune is a really great piece of work. Thank you very much!

(Also, regarding the items, I think it would be better to have my Little Legend just set move across the screen and then give the item to a random character. Then I think the game results will be a little better.)

**Comment by Kyrluckechuck** [comment]
@lolol0l I don't believe that's possible with the same League account since you can only be signed into one instance at a time. If you sign into the emulator first, it will be signed out when you launch the desktop client and vice versa

**Comment by Kyrluckechuck** [comment]
@lolol0l in that case I can't see any reason why it would, but definitely introduces a risk since Vanguard had started looking for executables running anything botting-related back when we first introduced those in https://github.com/Kyrluckechuck/TFT-Bot

**Comment by lolol0l** [comment]
I have to be careful. Thanks.
