### ISSUE TITLE
Is surrender feature any longer useful?

### ISSUE THREAD

**Issue by ErSangreh** [TeamFightTacticsBots/Alune#80]
Since xp gain is based on time played per game and your ranking, i think surrender strategy doesn't make sense right now. Early surrender just adds an extra time (queue+loading) in every game that could be used in game to earn some extra losing points (3/per min) or, maybe, even winning points (6/per min) xd.

Don't get me wrong, it's a nice to have feature, but some people could be tempted to use it, thinking they will get more points. And it could affect negatively this software reputation somehow.

Anyways, thank you for reading.

**Comment by akshualy** [comment]
Hello, this is why we in-depth explain in the config and when the bot is starting up for what you should be doing what. Playing out games is recommended for event passes that work off of time played, surrendering is faster if you *just* want the TFT pass levels as they are based on games played. Surrender is disabled by default, if you enable it you'll know what you're doing it for probably.
