### ISSUE TITLE
It's a new season.

### ISSUE THREAD

**Issue by kooo951** [TeamFightTacticsBots/Alune#83]
When is the new version coming out?
It's a new season.

**Comment by akshualy** [comment]
When I or someone else have time to do it.

**Comment by catasdd** [comment]
> When I or someone else have time to do it.

where can i get new season icons?

**Comment by Vesox33** [comment]
> When I or someone else have time to do it.

Any estimated time? Will be soooooo grateful

**Comment by catasdd** [comment]
hi i made png files of tft13
can add this?
[traits.zip](https://github.com/user-attachments/files/17847111/traits.zip)

**Comment by akshualy** [comment]
> Any estimated time? Will be soooooo grateful

Probably by the end of the weekend

> can add this?

In a PR, yes - you can check previous PRs on where stuff needs to be changed if you're interested in contributing. Here's an example: https://github.com/TeamFightTacticsBots/Alune/pull/28/files

**Comment by akshualy** [comment]
Released in https://github.com/TeamFightTacticsBots/Alune/releases/tag/v0.1.8
