### ISSUE TITLE
FF option 

### ISSUE THREAD

**Issue by Frostedhell** [TeamFightTacticsBots/Alune#87]
will there be an option to surrender  when possible ?

**Comment by Vesox33** [comment]
There is.
> surrender_early: false
You need to change this value for true in config file and then
> surrender_random_delay: 0
You need to set this value at 0.

**Comment by Akira0196** [comment]
Will surrendering every game be faster than playing normally to have a chance of making it into the top four?

**Comment by Vesox33** [comment]
If you are willing to farm normal pass it is better to not surrender.

**Comment by akshualy** [comment]
To elaborate:
Event passes have a repeating quest that rewards pass experience for the amount of time played League of Legends. This includes the amount of time you play TFT. The progress quests is rewarded double points from the time played if you win the game, which is being top 4 in TFT. Even if you would only be top 4 1 out of 10 games, it'd be more efficient than losing all 10 games (surrendering). Additionally, surrendering means you have to queue again, which takes time away from being in a game.
So no, for event passes surrendering is not faster.

**Comment by Akira0196** [comment]
Thank you all for your responses. I’d like to ask, ever since I started using version 0.1.8, the chances of making it to the top four have significantly decreased. Does anyone know why?
